<section>
	<h2>Mentions légales</h2>
		<h4>1. PRÉSENTATION DU SITE</h4>
			<p>Conformément à l'article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique, l'éditeur du site internet peut garder son anonymat, dès lors que les coordonnées exactes de l’éditeur ont été transmises de façon correcte à l’hébergeur. L'hébergeur est tenu de communiquer les informations sur l’éditeur, mais uniquement dans le cadre d’une procédure judiciaire.</p>
			<p>Hébergeur : OVH.COM - 2 rue Kellermann 59100 Roubaix</p>
		<h4>2. CONDITIONS GÉNÉRALES D'UTILISATION DU SITE ET DES SERVICES PROPOSÉS</h4>
			<p>L’utilisation du site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs du site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> sont donc invités à les consulter de manière régulière.</p>
			<p>Ce site est normalement accessible à tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut être toutefois décidée par <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a>, qui s’efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l’intervention.</p>
			<p>Le site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> est mis à jour régulièrement par son créateur. De la même façon, les mentions légales peuvent être modifiées à tout moment : elles s’imposent néanmoins à l’utilisateur qui est invité à s’y référer le plus souvent possible afin d’en prendre connaissance.</p>
		<h4>3. DESCRIPTION DES SERVICES FOURNIS</h4>
			<p>Le créateur du site s’efforce de fournir sur le site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> des informations aussi précises que possible. Toutefois, il ne pourra être tenu responsable des omissions, des inexactitudes et des carences dans la mise à jour, qu’elles soient de son fait ou du fait des tiers partenaires qui lui fournissent ces informations.</p>
			<p>Tous les informations indiquées sur le site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> sont données à titre indicatif, et sont susceptibles d’évoluer. Par ailleurs, les renseignements figurant sur le site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> ne sont pas exhaustifs. Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne.</p>
		<h4>4. LIMITATIONS CONTRACTUELLES SUR LES DONNÉES TECHNIQUES</h4>
			<p>Le site utilise la technologie JavaScript ainsi que les cookies.</p>
			<p>Le site Internet ne pourra être tenu responsable de dommages matériels liés à l’utilisation du site. De plus, l’utilisateur du site s’engage à accéder au site en utilisant un matériel récent, ne contenant pas de virus et avec un navigateur de dernière génération mis-à-jour</p>
		<h4>5. <!-- BOOBYTRAP THE STALEMATE BUTTON -->PROPRIÉTÉ INTELLECTUELLE ET CONTREFAÇONS</h4>
			<p>Le nom Minecraft, les logos Minecraft et les textures Minecraft sont la propriété intélectuelle et/ou des marques déposées de <a href="http://www.mojang.com/">Mojang</a>.</p>
			<p>Le créateur du site est propriétaire des droits de propriété intellectuelle ou détient les droits d’usage sur tous les éléments accessibles sur le site, notamment les textes, images, graphismes, logo, icônes, sons, logiciels. Les documents enregistrés par les utilisateurs du site qui sont sous la responsabilité des utilisateurs les ayant uploadés.</p>
			<p>Toute reproduction ou modification de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable du propriétaire du site.</p>
			<p>Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</p>
		<h4>6. LIMITATIONS DE RESPONSABILITÉ</h4>
			<p>Le créateur du site ne pourra être tenue responsable des dommages directs et indirects causés au matériel de l’utilisateur, lors de l’accès au site, et résultant soit de l’utilisation d’un matériel ne répondant pas aux spécifications indiquées au point 4, soit de l’apparition d’un bug ou d’une incompatibilité.</p>
			<p>Le créateur du site ne pourra également être tenu responsable des dommages indirects (tels par exemple qu’une perte de marché ou perte d’une chance) consécutifs à l’utilisation du site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a>.</p>
			<p>Des <a href="http://twitter.com/#!/ephysPotato/">espaces interactifs</a> (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs.</p>
			<p>Skin Manager n'est pas un outil officiel, approuvé, associé ou connecté à <a href="http://www.minecraft.net/">Minecraft.net</a>
		<h4>7. Gestion des données personnelles.</h4>
			<p>En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l'article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995.</p>
			<p> A l'occasion de l'utilisation du site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a>, peuvent êtres recueillies : l'URL des liens par l'intermédiaire desquels l'utilisateur a accédé au site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a>, le fournisseur d'accès de l'utilisateur, l'adresse de protocole Internet (IP) de l'utilisateur.</p>
			<p> En tout état de cause Guylian Cox ne collecte des informations personnelles relatives à l'utilisateur que pour le besoin de certains services proposés par le site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a>. L'utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu'il procède par lui-même à leur saisie. Il est alors précisé à l'utilisateur du site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> l’obligation ou non de fournir ces informations.</p>
			<p> Conformément aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, tout utilisateur dispose d’un droit d’accès, de rectification et d’opposition aux données personnelles le concernant, en effectuant sa demande écrite et signée, accompagnée d’une copie du titre d’identité avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse doit être envoyée.</p>
			<p> Aucune information personnelle de l'utilisateur du site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> n'est publiée à l'insu de l'utilisateur, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers. Seule l'hypothèse du rachat de Guylian Cox et de ses droits permettrait la transmission des dites informations à l'éventuel acquéreur qui serait à son tour tenu de la même obligation de conservation et de modification des données vis à vis de l'utilisateur du site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a>.</p>
			<p>Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.</p>
		<h4>8. Liens hypertextes et cookies.</h4>
			<p>Le site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> contient un certain nombre de liens hypertextes vers d’autres sites, mis en place avec l’autorisation de Guylian Cox. Cependant, Guylian Cox n’a pas la possibilité de vérifier le contenu des sites ainsi visités, et n’assumera en conséquence aucune responsabilité de ce fait.</p>
			<p> La navigation sur le site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> est susceptible de provoquer l’installation de cookie(s) sur l’ordinateur de l’utilisateur. Un cookie est un fichier de petite taille, qui ne permet pas l’identification de l’utilisateur, mais qui enregistre des informations relatives à la navigation d’un ordinateur sur un site. Les données ainsi obtenues visent à faciliter la navigation ultérieure sur le site, et ont également vocation à permettre diverses mesures de fréquentation.</p>
			<p> Le refus d’installation d’un cookie peut entraîner l’impossibilité d’accéder à certains services. L’utilisateur peut toutefois configurer son navigateur pour refuser l’installation des cookies.</p>
		<h4>9. Droit applicable et attribution de juridiction.</h4>
			<p>Tout litige en relation avec l’utilisation du site <a href="http://skinmanager.fr.nf/" title="http://skinmanager.fr.nf/">http://skinmanager.fr.nf/</a> est soumis au droit français. Il est fait attribution exclusive de juridiction aux tribunaux compétents de Paris.</p>
		<h4>10. Les principales lois concernées.</h4>
			<p>Loi n° 78-87 du 6 janvier 1978, notamment modifiée par la loi n° 2004-801 du 6 août 2004 relative à l'informatique, aux fichiers et aux libertés.</p>
			<p> Loi n° 2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique.</p>
		<h4>11. Lexique.</h4>
			<p>Utilisateur : Internaute se connectant, utilisant le site susnommé.</p>
			<p> Informations personnelles : « les informations qui permettent, sous quelque forme que ce soit, directement ou non, l'identification des personnes physiques auxquelles elles s'appliquent » (article 4 de la loi n° 78-17 du 6 janvier 1978).</p>
			<p>Uploader : Envoyer des données depuis un sytème local à un système distant, généralement un serveur.</p>
			<p><a href="http://www.minecraft.net/brand-guidelines">Minecraft Brand Guidelines</a></p>
			<p><a href="https://account.mojang.com/terms">Mojang Terms and Conditions</a></p>
</section>

<section>
	<h2>Conditions d'utilisation</h2>
		<h4>1. LEXIQUE</h4>
			<p>Le conditions d'utilisation de ce site utilisent une série de termes définis ci-après:</p>
			<p><i>Skin Manager</i>: Site web dont l'adresse est skinmanager.fr.nf</p>
			<p><i>Skin</i>: Image utilisé par le site www.minecraft.net et le jeu Minecraft&trade; définissant l'apparence d'un joueur. Le nom Minecraft est la propriété de Mojang.com</p>
			<p><i>TOS</i>: Term of Service, conditions d'utilisation</p>
		<h4>2. DESCRIPTION DES SERVICES</h4>
			<p>Skin Manager offre sur son site web la possibilité de gérer une galerie de skins personnelle, et de modifier le skin utilisé sur le compte Minecraft.net facilement.</p>
			<p>Ce site web permet d'accéder a de multiples skins accompagnés de leur description. Ceux-ci ne sont pas sous la responsabilité de Skin Manager mais uniquement sous celle de l'utilisateur les ayant mis en ligne sur Skin Manager</p>
			<p>En cas de contenu pouvant hurter la sensibilité des utilisateurs, contactez nous via la <a href="http://ephys.fr.nf/contact/">page de contact</a>. Le contenu sera retiré dans les plus brefs délais</p>
			<p>Afin d'utiliser les Services, il vous faut un accès Internet, soit directement accessible sur votre ordinateur, soit par l'intermédiaire d'autres supports tels que le téléphone mobile, les assistants personnels. Les éventuels frais correspondants à ces accès sont à votre seule charge. De plus, vous devez vous munir de tout matériel nécessaire afin d'assurer cette connexion au réseau Internet.</p>
		<h4>3. OBLIGATION D'INSCRIPTION ET D'IDENTIFICATION</h4>
			<p>L'utilisation des services proposés par Skin Manager nécessitent la possession d'un compte Skin Manager ainsi que la fourniture d'informations permettant l'identification de l'utilisateur, renseignées dans un formulaire d'inscription aux services.</p>
		<h4>4. POLITIQUE DE SKIN MANAGER EN MATIÈRE DE VIE PRIVÉE</h4>
			<p>Skin Manager accède à vos Données et les utilise dans l'unique but de vous permettre d'accéder aux Services et répondre à vos demandes concernant votre utilisation des Services.</p>
			<p>En cas de décès du titulaire d’un Compte Skin Manager et sur production de l’original d’un acte de décès relatif au titulaire du Compte Skin Manager, ce dernier sera désactivé, Skin Manager se réservant la possibilité de solliciter tout autre document nécessaire à cet égard.</p>
		<h4>5. COMPTE UTILISATEUR, MOT DE PASSE ET SÉCURITÉ</h4>
			<p>Le compte Skin Manager est créé via un formulaire d'inscription disponible sur le site de Skin Manager. Celui-ci est supprimable depuis le menu principal une fois l'utilisateur connecté. Lorsque cette action est effectuée, toutes les données vous concernant enregistrées sur le site seront effacées.</p>
			<p>Le mot de passe et le nom d'utilisateur de votre compte est géré par Skin Manager. En cas d'oubli des identifiants, un formulaire permettant de changer votre mot de passe est mis à disposition.</p>
		<h4>6. COMPORTEMENT DES UTILISATEURS ET PROTECTION DES MINEURS</h4>
			<p>Vous êtes responsable de tout Contenu que vous stockez sur des espaces personnels ou accessibles à des tiers des Services fournis par Skin Manager.</p>
			<p>Vous êtes par ailleurs conscient que tout contenu accessible au public mis en ligne par un des utilisateurs des Services relève de la responsabilité de celui-ci, Skin Manager n'exerçant pas de contrôle a priori sur lesdits Contenus. Skin Manager n'a pas d'obligation générale de surveillance du contenu stocké sur ses Services par les utilisateurs.</p>
		<h4>7. MODIFICATION DES SERVICES ET DES CONDITIONS GENERALES D'UTILISATION</h4>
			<p>L'offre de services du Site Skin Manager est évolutive et Skin Manager sera amené à lancer de nouveaux services, mais aussi le cas échéant, à en supprimer certains ou à modifier les caractéristiques des services existants, selon les conditions ci-après énoncées. Skin Manager pourra également modifier les présentes TOS.</p>
			<p>Les utilisateurs qui n'accepteront pas ces modifications pourront résilier leur compte selon la procédure décrite à l'article 8 des TOS. Cette résiliation pourra être effectuée à tout moment. En l'absence d'une telle résiliation, les modifications des Services seront opposables aux utilisateurs dès leur entrée en vigueur.</p>
		<h4>8. RÉSILIATION</h4>
			<p>Tout utilisateur peut résilier son Compte Skin Manager à tout moment en ouvrant une session avec ses Nom de Compte et mot de passe et en cliquant sur le bouton prévu à cet effet dans le menu principal. Une fois l'action confirmée, le compte sera éffacé et l'utilisateur déconnecté.</p>
			<p>Cette résiliation entraînera automatiquement l'inaccessibilité de l'ensemble des Contenus stockés sur les Services. il est conseillé aux utilisateurs de procéder préalablement à la sauvegarde de leurs contenus sur un autre compte ou sur tout support de leur choix.</p>
			<p>En cas de manquement à l'une des obligations essentielles découlant des TOS, Skin Manager sera en droit, sans notification préalable et avec effet immédiat, de désactiver votre Compte Skin Manager, ce qui entraînera automatiquement l'inaccessibilité définitive de tous vos Contenus.</p>
		<h4>9. RESPONSABILITÉ</h4>
			<p>La responsabilité de Skin Manager ne peut être engagée du fait de tiers, en particulier quant aux contenus ou Services Tiers fournis par des prestataires tiers, ou du fait de la présence de Contenu mis en ligne par les utilisateurs et accessibles sur les Services.</p>
			<p>La responsabilité de Skin Manager ne pourra être davantage engagée, sans que cette liste ne soit exhaustive, du fait de la perte de profits, de données ou informations stockées sur les Services, ni du fait de dommages indirects. L'ensemble des utilisateurs étant par ailleurs invités à conserver une copie de sauvegarde de toutes les données et Contenus stockés sur les Services.</p>
			<p>Vous acceptez de défendre et de dégager de toute responsabilité Skin Manager et ses filiales, membres de la direction, agents, sous-traitants, employés, partenaires, et concédants de licence vis-à-vis de toute réclamation ou plainte, y compris frais d’avocat et de justice, qui serait présentée sur la base des contenus que vous envoyez, stockez, publiez, transmettez, modifiez ou mettez à disposition d’une manière ou d’une autre via les Services, de votre utilisation des Services, de vos connexions aux Services, d’une infraction de votre part aux présentes TOS, d’une violation de votre part des lois applicables ou d’une atteinte de votre part aux droits d’une autre personne physique ou morale.</p>
		<h4>10. SERVICE CLIENTÈLE</h4>
			<p>En cas de difficulté technique, de propositions, d'idées à proposer ou de réclamation, vous pouvez contacter le titulaire du site, @EphysPotato, via son <a href="http://ephys.fr.nf/">site Internet ephys.fr.nf</a> ou via son <a href="http://twitter.com/EphysPotato">compte twitter</a>.
		<p>Version 0.3 - 29 juillet 2013</p>
</section>